### ISSUE TITLE
post not showing up (e621)(electron app)

### ISSUE THREAD

**Issue by 99spooner** [DontTalkToMeThx/BooruSlideshow#1]
so im not sure if e621 is still updating thier stuff or what not but when i try to search images i dont get the same amount i would get on the site , for example when i search for the character [dobie_gray](https://e621.net/posts?tags=dobie_gray) on the site itself i get 28 results but when i do it through the app i only get [14 results](https://imgur.com/a/xX3EdNa). it also happening to a less extent on the regular add-on (on firefox)  as when i search the it through there i only get 27 results (also with no blacklisted terms)

**Comment by DontTalkToMeThx** [comment]
Some posts you have to be logged in to view, I'll see if they implemented this into their api yet.

As you can see when you aren't logged in, you will get:
https://oliy.is-just-a.dev/udsq1aq_3082.png

**Comment by 99spooner** [comment]
That makes sense it's similar to gelbooru

**Comment by DontTalkToMeThx** [comment]
> That makes sense it's similar to gelbooru

Yep, but you can log in to them (which I never did test as I don't have an account. I'll make sure to test that along with this update)

**Comment by 99spooner** [comment]
Is there anyway to log in to e621 or gelbooru in the app at this time?

**Comment by DontTalkToMeThx** [comment]
> Is there anyway to log in to e621 or gelbooru in the app at this time?

I didn't know about the e621 one, so no for that. Gel I'm not sure, but most likely not. I will fix these when I get time.

**Comment by DontTalkToMeThx** [comment]
I was able to fix e621. I'll look more into gelbooru when I have the time. I'll get that uploaded asap.

**Comment by DontTalkToMeThx** [comment]
I'm gonna close this, if it didn't work feel free to open it again.
