### ISSUE TITLE
Minor Improvement - Changing E6 return URL

### ISSUE THREAD

**Issue by JezzaR-The-Proto** [DontTalkToMeThx/BooruSlideshow#10]
I've noticed that when clicking on an image for e621, it takes you to https://e621.net/post/show/{postID}. This has been depreciated for a while and should be changed with https://e621.net/posts/{postID}.
Specifically, I've found changing `var url = this.url + '/post/show/' + jsonPost.id;` in site_manager_e621.js to `var url = this.url + '/posts/' + jsonPost.id;` works nicely.

**Comment by DontTalkToMeThx** [comment]
This is now implemented, I suggest next time that you open a pull request so you can get put on the contributors list.

**Comment by JezzaR-The-Proto** [comment]
Ah ok, I'll do that next time/=

**Comment by DontTalkToMeThx** [comment]
All good, you just get added to the contributors if you do that, and people that help should be added, but I don't think I can manually.
