### ISSUE TITLE
Latest Update, Not working in Incognito 

### ISSUE THREAD

**Issue by pointlessname99** [DontTalkToMeThx/BooruSlideshow#15]
Yes, I went into Chrome's setting for Booru Slideshow and enabled "Allow in Incognito" even tried disabling and re-enabling it.

Basically, a new update happens and now whenever I click the extension it opens a new window in the non-incognito mode

**Comment by DontTalkToMeThx** [comment]
c86f891b17c50283d911604aba17e201e6daba28 should work
