### ISSUE TITLE
FIx - ATFBooru is down, with "Error making the request to https://atfbooru.ninja/posts.json?tags=a&page=1&limit=100"

### ISSUE THREAD

**Issue by BigBonger** [DontTalkToMeThx/BooruSlideshow#17]
Everytime I search for anything atfbooru will error and show

**Error making the request to https://atfbooru.ninja/posts.json?tags=a&page=1&limit=100**

I'm currently trying to fix this issue but can't seem to figure it out.

**Comment by DontTalkToMeThx** [comment]
Should be fixed
