### ISSUE TITLE
a possible feature and question (partially electron app)

### ISSUE THREAD

**Issue by 99spooner** [DontTalkToMeThx/BooruSlideshow#2]
First off i just want to say a big thank you for what you are doing.
im curious if 2 things are possible, you dont have to do them if you dont think you can just curious 

1. is  it possible to add a button or something that would allow for multiples of the same image from multiple sites, this was possible in previous versions of the original add on up until version 7.14 when changes were made

2. this one is less likely but im just curious, is there anyway to hide the white bar on the top of the electron app when in full screen.

also just want to say sorry if im asking too much from you with all that you have done, i have nearly next to no knowledge of coding or any of the things done to make an extension or app work so you are a big help

**Comment by DontTalkToMeThx** [comment]
Can you take a picture of whatyou mean by the bar? (I'm not currently home) and the switch for allowing multiple of the same images might be doable but as it isn't all my code, I'll have to do some digging, but if it's a possibility, sure.

**Comment by 99spooner** [comment]
its the white one on the top with file, edit, view, window and help. [Pic](https://imgur.com/a/quiXwbZ), i dont think its possible but hey it cant hurt to ask.

**Comment by DontTalkToMeThx** [comment]
@99spooner yeah that's possible, should just be one line, I was looking into it yesterday.

**Comment by DontTalkToMeThx** [comment]
About allowing duplicates: it's all based on md5 hashes, so I will be able to allow duplicates, but I won't be able to let you duplicate it into your favorites list if it's already on there.

**Comment by 99spooner** [comment]
That's fine

**Comment by DontTalkToMeThx** [comment]
Win32x64 version is now live [here](https://cdn.is-just-a.dev/booruslideshowelectron-win32-x64.zip) make sure to clear cache to ensure it's the newest version. Other versions will be live within 24 hours [here](https://cdn.is-just-a.dev/)

Extension will be updated within 10 minutes. Reopen this if it didn't work for you.

**Comment by 99spooner** [comment]
ok we have a slight problem now, the duplicates part seems to work fine but now im not able to put the app into full screen mode by pressing f11, im guessing since the white bar at the top was removed im not able to do it anymore, if there is anything that you can do please try but if not just put the white bar back (assuming its the reason i cant go fullscreen)

**Comment by DontTalkToMeThx** [comment]
Yeah removing the menu seemed to have removed all key short cuts, I'll add fullscreen back (if possible) when I get time tomorrow, in the meantime, you *might* be able to fullscreen a webm thwn scroll down to search, not sure though

**Comment by 99spooner** [comment]
Thanks, if possible you might also want to add back in the menu that had the cut paste and copy buttons or something similar as the api keys for e621 and derpibooru are a bit long and I would be easier if we could just copy and paste them from the sites

**Comment by DontTalkToMeThx** [comment]
I believe that also came from the menu, I'll add back fullscreen (F11) copy (ctrl+c) and paste (ctrl+v) tomorrow. If you can think of any other shortcuts, please tell me so I don't have to make multiple updates. All the shortcuts for the app work though, right? (Arrow keys, WASD, L, etc.)

**Comment by 99spooner** [comment]
yeah all of the the keys listed under hotkeys seem to work fine (besides full screen of course). also i had forgotten about the keyboard shortcuts for copy and paste and tested them both and they both work fine so all you need to worry about is fullscreen,

**Comment by DontTalkToMeThx** [comment]
All right, I'll work on it tomorrow when I get time.

**Comment by DontTalkToMeThx** [comment]
Uploading Windows 64 bit fix now. I will update all other versions within 24 hours of this comment.
ETA on Windows x64 10 minutes

**Comment by DontTalkToMeThx** [comment]
Reopen and comment if it doesn't work.
