### ISSUE TITLE
Results Slow to Load/Timing Out

### ISSUE THREAD

**Issue by idfi** [DontTalkToMeThx/BooruSlideshow#3]
I downloaded this since e621 was no longer working on the original version. However, I'm having issues with results either being really slow to load or not loading at all no matter how long I wait. I do not have this issue with the original version. Any insights as to what may be going on here/how to fix this would be appreciated.

**Comment by BrandonRubadeau** [comment]
I'm also having the issue with slow loading times. I thought it was just my ISP slowing it down, but seeing how I'm not the only one with this issue I guess it has some other problem.

**Comment by DontTalkToMeThx** [comment]
We'll see if my most recent commit fixes this. If it doesn't reopen and I'll look into it further.
