### ISSUE TITLE
only preloading 6 images ahead (Electron app)

### ISSUE THREAD

**Issue by 99spooner** [DontTalkToMeThx/BooruSlideshow#4]
not sure if this is something that you did or if its a bug but just curious.

when the images preload (when the small thumbnails get color) they only seems to load up to the 6th image excluding the one you start one and no matter how long i wait it wont load, while its not that big a problem as when i got to them next image the next one after the 6th gets loaded it can get annoying when i want to go through images quickly and i also prefer to have more preloaded then not

**Comment by idfi** [comment]
This is part of the issue that I mention in my post.

**Comment by DontTalkToMeThx** [comment]
Please direct all electron bugs to the [electron repo](https://github.com/DontTalkToMeThx/BooruSlideshowElectron/issues) I will get to fixing this issue for both platforms soon.

**Comment by DontTalkToMeThx** [comment]
Should be fixed, reopen if not. (Electron app will be updated within the next 24 hours, so please wait until at least then to reopen)
