### ISSUE TITLE
derpibooru no long working

### ISSUE THREAD

**Issue by fakesuffs** [DontTalkToMeThx/BooruSlideshow#6]
just wanted to bring to light an API change that makes derpibooru no longer functional. wondering if there will be a fix, thank you

**Comment by gmasil** [comment]
Hi, I fixed it and created a PR. You can find it here until the PR is merged: https://github.com/gmasil/BooruSlideshow

**Comment by DontTalkToMeThx** [comment]
> Hi, I fixed it and created a PR. You can find it here until the PR is merged: https://github.com/gmasil/BooruSlideshow

Thank you, will merge.
