### ISSUE TITLE
Thanks for updating.....

### ISSUE THREAD

**Issue by hpcjosh** [DontTalkToMeThx/BooruSlideshow#7]
Thanks for updating the extension but is there any chance to install this software on firefox?

**Comment by DontTalkToMeThx** [comment]
It already exists, but I haven't been able to get it reviewed by firefox to make it public.

**Comment by DontTalkToMeThx** [comment]
Alternatively, download [this file](https://cdn.is-just-a.dev/BooruSlideshow.xpi), head to [about:addons](about:addons) in firefox, click the cog then install add-on from file and find the xpi you downloaded and try that.

**Comment by hpcjosh** [comment]
Yes the xpi files does indeed work, it still has the gelbooru issue, that's in the Chromium version but otherwise everything is okay with it.

**Comment by DontTalkToMeThx** [comment]
I believe I fixed it, you'll need to redownload it and readd it to firefox. Reopen this issue if it still doesn't work
