### ISSUE TITLE
Choosing "Include Safe" and deselecting "Include Questionable and Include Explicit" doesn't work.

### ISSUE THREAD

**Issue by JezzaR-The-Proto** [DontTalkToMeThx/BooruSlideshow#8]
![Only "Include Safe" is selected](https://user-images.githubusercontent.com/54776821/84706326-acd56000-af54-11ea-9ec8-3961445bedc9.png)
![Getting Explicit Image](https://user-images.githubusercontent.com/54776821/84706353-b8288b80-af54-11ea-86d7-eb59c087b9df.png)
![It is rated explicit on gelbooru](https://user-images.githubusercontent.com/54776821/84706411-d098a600-af54-11ea-907b-caf0185f0696.png)
Whatever check you are doing to make sure an image is safe obviously isnt working, I would recommend just sending the tag "rating:safe" and whatnot along with the get request, this would probably solve most of the issues.

**Comment by DontTalkToMeThx** [comment]
That would work, but on some sites, it decreases the search tags by some amount so I filter them afterwards, I must've missed it for that site (mainly because I don't have a gelbooru account so I've never been able to test it, but I'll look into it

**Comment by DontTalkToMeThx** [comment]
Or... it may be because I never added the filter code to gelbooru because I don't have a brain

**Comment by DontTalkToMeThx** [comment]
Just pushed a new commit that should fix this, if it doesn't, reopen this issue.
